front/companies/urls.py
from django.conf.urls import url
from . import views

app_name = 'front'

urlpatterns = [
    #/partywizards/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/partywizards/contact/
    url('^contact/$', views.ContactView.as_view(), name='contact'),

    #/partywizards/about/
    url('^about/$', views.AboutView.as_view(), name='about'),

]

front/front/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from  django.conf import  settings
from  django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^partywizards/', include('companies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

partywizards/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from  django.conf import  settings
from  django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('wizapp.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wizapp/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views



app_name = 'wizapp'

urlpatterns = [
    # / - index
    url(r'^$', views.IndexView.as_view(template_name="index.html"), name='index'),

    url(r'^drinks/$', views.DrinkIndexView.as_view(), name="drinks"),

    url(r'^(?P<pk>[0-9]+)/$', views.DrinkDetailView.as_view(), name='detail'),

    url(r'^drinks/add/$', views.AddDrinkView.as_view(), name="drink-add"),

    # /barcode
    url(r'^barcode/$', views.BarcodeView.as_view(),name="barcodes"),

    # /barcode/add/
    url(r'^barcode/add/$', views.BarcodeAdd.as_view(),name="barcode-add")
]

front/companies/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

wizapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Drink(models.Model):
    name =  models.CharField(max_length=250, blank=False)
    recipe = models.CharField(max_length=1000)
    picture = models.FileField(blank=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wizapp:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name



class Ingredient(models.Model):
    name =  models.CharField(max_length=250, blank=False)
    kind = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Tool(models.Model):
    name = models.CharField(max_length=250, blank=False)
    kind = models.CharField(max_length=250)
    picture = models.FileField(blank=False)

    def __str__(self):
        return self.name

class Decoration(models.Model):
    name = models.CharField(max_length=250, blank=False)
    picture = models.FileField(blank=False)

    def __str__(self):
        return self.name

class Barcode(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    barcode = models.IntegerField(blank=False)

    def __str__(self):
        return self.barcode

class ListIngredients(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField()
    kindMeasure = models.CharField(max_length=20)

    def __str__(self):
        return self.quantity + ' - ' + self.kindMeasure

class ListTools(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)

class ListDecoration(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    decoration = models.ForeignKey(Decoration, on_delete=models.CASCADE)

class Rating(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    user = models.ForeignKey(User)
    rating = models.IntegerField();

    def __str__(self):
        return self.rating

class Comment(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    user = models.ForeignKey(User)
    comment = models.CharField(max_length=1000, blank=False)
    date = models.DateField(auto_now_add=True)
    delete = models.BooleanField(default=False)

    def __str__(self):
        return self.comment + ' - ' + self.date

class Answer(models.Model):
    answer_comment = models.ForeignKey(Comment)
    comment = models.CharField(max_length=1000, blank=False)
    date = models.DateField(auto_now_add=True)
    delete = models.BooleanField(default=False)

    def __str__(self):
        return self.comment + ' - ' + self.date


class Ban(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    perm = models.BooleanField(default=False)

    def __str__(self):
        return self.start_date + ' - ' + self.end_date


class myUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_moderator = models.BooleanField(default=False)
    date_of_birthday = models.DateField()
    sex = models.CharField(max_length=10)
    age = models.IntegerField()

front/companies/views.py
from django.views import  generic
from django.shortcuts import render

class IndexView(generic.TemplateView):
   template_name = 'front/index.html'

class ContactView(generic.TemplateView):
   template_name = 'front/contact.html'

class AboutView(generic.TemplateView):
   template_name = 'front/about.html'

wizapp/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Barcode
from .models import Drink

class IndexView(generic.TemplateView):
    template_name = 'index.html'

class BarcodeView(generic.ListView):
    context_object_name = 'barcodes_all'
    model = Barcode
    template_name = 'barcodes.html'

class BarcodeAdd(CreateView):
    model = Barcode
    fields = ['barcode', 'ingredient']
    success_url = reverse_lazy('wizapp:barcodes')

class DrinkIndexView(generic.ListView):
    model = Drink
    context_object_name = 'all_drinks'
    template_name = 'drink_index.html'

    def get_queryset(self):
        return Drink.objects.all()

class AddDrinkView(CreateView):
    model = Drink
    fields = ['name', 'recipe', 'picture' ]

class DrinkDetailView(generic.DetailView):
    model = Drink
    template_name = 'detail.html'

'''

def index(request):
    return HttpResponse("Hello, world. You're at the wizards new home.")

'''

front/companies/templates/front/about.html
{% extends 'front/base.html' %}
{% block title %}About{% endblock %}
{% block active_about %} class="active" {% endblock %}

{% block body %}
 <!-- Side nav -->
    <nav class="side-nav" role="navigation">

      <ul class="nav-side-nav">
        <!--<li><a class="tooltip-side-nav" href="#section-1" title="" data-original-title="Services" data-placement="left"></a></li>-->
        <li><a class="tooltip-side-nav" href="#section-2" title="" data-original-title="Features" data-placement="left"></a></li>
        <li><a class="tooltip-side-nav" href="#section-3" title="" data-original-title="Subscribe" data-placement="left"></a></li>
        <li><a class="tooltip-side-nav" href="#to-top" title="" data-original-title="Back" data-placement="left"></a></li>
      </ul>

    </nav> <!-- /.side-nav -->




    <!-- Jumbotron -->
    <header class="jumbotron" role="banner">
      <section  id="to-top">
      <div class="container">

        <div class="row">

          <div class="col-md-7">

            <!-- Logo -->
            <figure class="text-center">
              <a href="#">
                <img class="img-logo" src="../../static/front/images/logo.png" alt="">
              </a>
            </figure> <!-- /.text-center -->

            <!-- Title -->
            <h1>Who we are</h1>

            <!-- Sub title -->
            <p>We are the greatest wizards on the world. We help you create the crazy potions.</p>

            <!-- Button -->
            <p class="btn-app-store">
              <a class="btn btn-danger btn-lg" href="#fakelinks">
                <img src="../../static/front/images/btn-app-store.png" alt="">
              </a>
            </p> <!-- /.btn-app-store -->

          </div> <!-- /.col-md-7 -->

          <div class="col-md-5">

            <!-- Images showcase -->
            <figure>
              <img class="img-iPhone" src="../../static/front/images/iphone/dr2.jpg" alt="">
            </figure>

          </div> <!-- /.col-md-5 -->

        </div> <!-- /.row -->

      </div> <!-- /.container -->
      </section>

    </header> <!-- /.jumbotron -->


    <!-- Features -->
    <section class="features-section" id="section-2">

      <div class="container">

        <div class="row">

          <div class="col-md-5 col-features text-center">

            <!-- Images showcase -->
            <figure>
              <img class="img-iPhone" src="../../static/front/images/iphone/dr11.jpg" alt="">
            </figure>

          </div> <!-- /.col-md-5 -->

          <div class="col-md-7 col-features features-content">

            <!-- Title -->
            <h3 id="title-1">How good we are</h3>

            <!-- Description -->
            <p>Ask Gandalf</p>

            <p>
              <a class="btn btn-danger" href="#title-2">Learn more</a>
            </p>

          </div> <!-- /.col-md-7 -->

        </div> <!-- /.row -->




        <div class="row media-screen-800">

          <div class="col-md-7 col-features features-content">

            <!-- Title -->
            <h3 id="title-2">Recommend by Deadpool</h3>

            <!-- Description -->
            <p>cenzura</p>

            <p>
              <a class="btn btn-danger" href="#">Sign In</a> &nbsp;
              <a class="btn btn-danger-border" href="#">Sign Up</a>
            </p>

          </div> <!-- /.col-md-7 -->

          <div class="col-md-5 col-features text-center">

            <!-- Images showcase -->
            <figure>
              <img class="img-iPhone margin-top margin-screen-800" src="../../static/front/images/iphone/dr3.jpg" alt="">
            </figure>

          </div> <!-- /.col-md-5 -->

        </div> <!-- /.row -->




        <div class="row">

          <div class="col-md-5 col-features text-center">

            <!-- Images showcase -->
            <figure>
              <img class="img-iPhone margin-top margin-top-1" src="../../static/front/images/iphone/drunk5.gif" alt="">
            </figure>

          </div> <!-- /.col-md-5 -->

          <div class="col-md-7 col-features features-content">

            <!-- Title -->
            <h3 id="title-3">My pet is hunger</h3>

            <!-- Description -->
            <p>Get App or my skull eat you</p>

            <!-- Button -->
            <p class="btn-app-store">
              <a class="btn btn-danger btn-lg" href="#fakelinks">
                <img src="../../static/front/images/btn-app-store.png" alt="">
              </a>
            </p> <!-- /.btn-app-store -->

          </div> <!-- /.col-md-7 -->

        </div> <!-- /.row -->

      </div> <!-- /.container -->

    </section> <!-- /.features-section -->




    <!-- Subscribe -->
    <section class="subscribe-section" id="section-3">

      <div class="container">

        <div class="row">

          <div class="col-md-12">

            <!-- Title -->
            <h2>Don't forget brush teeth and suncribe us</h2>

            <!-- Subscribe form -->
            <div class="row">

              <div class="col-md-6 col-md-offset-3 col-subscribe">

                <form class="subscribe-form form-inline" action="#" role="form">

                  <!-- Input -->
                  <div class="form-group">

                    <label class="sr-only" for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email address">

                  </div> <!-- /.form-group -->

                  <!-- Button -->
                  <button class="btn btn-success" type="submit">Subscribe</button>

                </form> <!-- /.subscribe-form -->


`
                <section class="subscribe-description">

                  <p>Don't worry. We do not spam :)</p>

                </section> <!-- /.subscribe-description -->

              </div> <!-- /.col-md-6 -->

            </div> <!-- /.row -->

          </div> <!-- /.col-md-12 -->

        </div> <!-- /.row -->

      </div> <!-- /.container -->

    </section> <!-- /.subscribe-section -->




    <!-- Footer -->
    <footer class="footer-section" role="contentinfo">

      <div class="container">

        <div class="row">

          <div class="col-md-4 col-footer">

            <!-- Footer 1 -->
            <section>
              <p>Made with <i class="fa fa-heart"></i> by Aryandhani.</p>
            </section>

            <!-- AddThis Button -->
            <ul class="addthis_toolbox addthis_default_style">

              <li><a class="addthis_button_facebook_like"></a></li>
              <li><a class="addthis_button_tweet"></a></li>

            </ul> <!-- /.addthis_toolbox -->
            <script>var addthis_config = {"data_track_addressbar":true};</script>
            <script src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-533f6ac03b59c72a"></script>

          </div> <!-- /.col-md-4 -->

          <div class="col-md-4 col-footer col-padding">

            <!-- Footer 1 -->
            <section class="text-center">
              <p>Be sure to read <a href="#fakelinks">Terms</a> and <a href="#fakelinks">Privacy Policy</a>.</p>
            </section>

            <!-- Social media links -->
            <ul class="social-media-links">

              <li><a class="fa fa-twitter tw" href="#fakelinks"></a></li>
              <li><a class="fa fa-facebook fb" href="#fakelinks"></a></li>
              <li><a class="fa fa-pinterest pn" href="#fakelinks"></a></li>

            </ul> <!-- /.social-media-links -->

          </div> <!-- /.col-md-4 -->

          <div class="col-md-4 col-footer">

            <!-- Footer 1 -->
            <section>
              <!--  <p><strong>Guri Guri Nyoi, Inc</strong> <br>Antah berantah Street, Block 123 <br>Dimana saja, Kapan saja, 12356.</p>-->
             </section>

           </div> <!-- /.col-md-4 -->

        </div> <!-- /.row -->

      </div> <!-- /.container -->

    </footer> <!-- /.footer-section -->
    {% load staticfiles %}
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'front/javascript/vendor/jquery-2.1.0.min.js' %}"></script>
    <script src="{% static 'front/javascript/bootstrap.min.js' %}"></script>
    <script src="{% static 'front/javascript/assets/application.js' %}"></script>
{% endblock %}

front/companies/templates/front/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="Deinonzch" content="">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="icon" href="../../favicon.ico"/>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'front/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}"/>
    <!-- Bootstrap theme -->
    <link rel="stylesheet" type="text/css" href="{% static 'front/bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}"/>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'front/bootstrap-3.3.6-dist/css/ie10-viewport-bug-workaround.css' %}"/>

    <!-- Templates core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'front/stylesheets/application.css' %}"/>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'front/stylesheets/theme.css' %}"/>

    <!-- Favicons -->
    <link href="images/favicon/favicon.png" rel="shortcut icon">
    <link href="images/favicon/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon">
    <link href="images/favicon/apple-touch-icon-72-precomposed.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/favicon/apple-touch-icon-144-precomposed.png" rel="apple-touch-icon" sizes="114x114">

    <!--
    Just for debugging purposes. Don't actually copy these 2 lines!
    [if lt IE 9]<script src="../../assets/js/ie8-responsive-file-warning.js"></script>[endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->

   <script src="{% static 'front/javascript/vendor/modernizr-2.7.1.min.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body role="document">

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'front:index' %}">Party Wizards</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% block active_about %} {% endblock %}><a href="{% url 'front:about' %}">About</a></li>
                <li {% block active_contact %} {% endblock %}><a href="{% url 'front:contact' %}">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span><b> Login</b> <span class="caret"></span></a>
                    <ul id="login-dp" class="dropdown-menu">
                        <li>
                            <div class="row">
                                <div class="col-md-12">
                                    Login via
                                    <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
                                        <div class="form-group">
                                            <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                            <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
                                        </div>
                                        <div class="form-group">
                                            <label class="sr-only" for="exampleInputPassword2">Password</label>
                                            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                            <div class="help-block text-right"><a href="">Forget the password ?</a></div>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> keep me logged-in
                                            </label>
                                        </div>
                                    </form>
                                </div>
                                <div class="bottom text-center">
                                    New here ? <a href="#"><b>Join Us</b></a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

{% block body %}
{% endblock %}

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<<!--script type="text/javascript" src="lokalizacja skryptu"></script>-->
<!--<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>-->
<script src="{% static 'front/bootstrap-3.3.6-dist/js/bootstrap.min.js' %}"></script>
<!--<script src="../../assets/js/docs.min.js"></script>-->
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->
</body>
</html>

front/companies/templates/front/contact.html
{% extends 'front/base.html' %}
{% block title %}Contact{% endblock %}
{% block active_contact %} class="active" {% endblock %}

{% block body %}
<div class="container theme-showcase" role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>E-mail</h1>
        <p>partywizards@gmail.com</p>
        <h1>Adres</h1>
        <p>ulica Pokątna 39</p>
    </div>

</div> <!-- /container -->
{% endblock %}

front/companies/templates/front/index.html
{% extends 'front/base.html' %}
{% block title %}Party Wizards{% endblock %}

{% block body %}
<div class="container theme-showcase" role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>Welcome</h1>
        <p>We are the greatest wizards on the world. We help you create the crazy potions.</p>
    </div>

</div> <!-- /container -->
{% endblock %}

wizapp/templates/barcodes.html
{% extends 'base.html' %}

{% block title %} Barcodes {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% for barcode in barcodes_all %}
                            <li>
                                <span>Bar: {{ barcode.barcode }} jest przypisany do: {{ barcode.ingredient.name }} o typie: {{ barcode.ingredient.kind }}</span>
                            </li>
                        {% endfor %}
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock %}

wizapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Wizard of Party{% endblock %} </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'wizapp/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div flass="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'wizapp:index' %}">Driny</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'wizapp:drinks' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Driny
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'wizapp:drink-add' %}">
                        <span class="glyphicon glyphicon-glass" aria-hidden="true"></span>&nbsp; Dodaj alko
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'wizapp:barcodes' %}">
                        <span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>&nbsp; Barcodes
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'wizapp:barcode-add' %}">
                        <span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>&nbsp; Add barcode
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="% url 'wizapp:index' %">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>


    </div>

</nav>
{% block body %}
{% endblock %}


</body>
</html>

wizapp/templates/detail.html
{% extends 'base.html' %}
{% block title %}{{ drink }}{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'wizapp:detail' drink.id %}">
                        {% if drink.picture %}
                            <img src="{{ drink.picture.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ drink.name }} </h1>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

wizapp/templates/drink_index.html
{% extends 'base.html' %}

{% block title %} Drinks {% endblock %}

{% block body %}

{% if all_drinks %}
{% for drink in all_drinks %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'wizapp:detail' drink.id %}">
                            <img src="{{ drink.picture.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ drink.name }}</h2>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
{% endif %}
{% endblock %}

wizapp/templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

wizapp/templates/index.html
{% extends 'base.html' %}

{% block title %} Wizards of Party Home {% endblock %}

{% block body %}
Hello world template!
{% endblock %}

wizapp/templates/wizapp/barcode_form.html
{% extends 'base.html' %}

{% block title %}Add Barcode{% endblock %}

{% block body %}


<div class="container-fluid">
    <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class = "form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock %}

wizapp/templates/wizapp/drink_form.html
{% extends 'base.html' %}

{% block title %}Add Drink{% endblock %}

{% block body %}


<div class="container-fluid">
    <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class = "form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock %}